apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: flipbook-dev
data:
  APP_NAME: "Flipbook SaaS"
  DEBUG: "False"
  API_VERSION: "v1"
  DATABASE_URL: "postgresql://flipbook:PASSWORD_PLACEHOLDER@postgresql.flipbook-dev.svc.cluster.local:5432/flipbook"
  REDIS_URL: "redis://redis.flipbook-dev.svc.cluster.local:6379/0"
  MINIO_ENDPOINT: "minio.flipbook-dev.svc.cluster.local:9000"
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECURE: "False"
  CELERY_BROKER_URL: "redis://redis.flipbook-dev.svc.cluster.local:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis.flipbook-dev.svc.cluster.local:6379/0"
